version: '3'
services:
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/home/main/
      - ./left-side/:/home/left-side/
      - ./right-side/:/home/right-side/
    ports:
      - 8000:8000
      - 2000:2000
      - 3000:3000
    networks:
      - nginx_network
networks:
  nginx_network:
    external: true
